#define CA_CIRC KC_LBRC          // ^ (dead)
#define CA_DIAE S(CA_CIRC)       // ¨ (dead)
#define CA_GRV  ALGR(CA_CIRC)    // ` (dead)
#define CA_DTIL ALGR(CA_CCED)    // ~ (dead)
#define CA_CEDL RCTL(CA_EQL)     // ¸ (dead)
#define CA_ACUT RCTL(CA_SCLN)    // ´ (dead)
#define CA_OGON RCTL(S(CA_EQL))  // ˛ (dead)
#define CA_MACR RCTL(S(CA_CCED)) // ¯ (dead)
#define CA_DACU RCTL(S(CA_SCLN)) // ˝ (dead)
#define CA_CARN RCTL(S(CA_EGRV)) // ˇ (dead)
#define CA_BREV RCTL(S(CA_AGRV)) // ˘ (dead)

#define CA_DOTA RCTL(CA_DOT)     // · (dead)
#define CA_RNGA RCTL(S(CA_CIRC)) // ˚ (dead)
